### ISSUE TITLE
no sass gem found

### ISSUE THREAD

**Issue by wiktorschmidt** [netguru/review-chrome-extension#2]
when doing make after clean make setup

    mkdir -pv build/stylesheets/
    ruby_gems/bin/sass --cache-location tmp/sass-cache src/stylesheets/main.scss build/stylesheets/main.css
    /Users/xxx/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'sass' (>= 0) among 99 total gem(s) (Gem::LoadError)

**Comment by mamut** [comment]
does not apply anymore since we switched to ember-cli pipeline
